"""Market Outlook Module.

Provides probabilistic short-term market outlooks based on current regime
and strategy outperformance probabilities.
"""

from __future__ import annotations
import pandas as pd

def get_market_outlook(
    df: pd.DataFrame, 
    current_regime: str, 
    strategy_probs: dict[str, float]
) -> dict[str, any]:
    """Calculate a probabilistic market outlook.
    
    Args:
        df: Historical data with features.
        current_regime: Current market regime (Bull, Bear, Sideways).
        strategy_probs: ML probabilities of strategies outperforming Buy & Hold.
        
    Returns:
        Dictionary with outlook, probability, confidence, and disclaimer.
    """
    # 1. Base probability from regime
    regime_scores = {
        "Bull": 0.72,      # Bullish default
        "Sideways": 0.50,  # Neutral default
        "Bear": 0.28       # Bearish default
    }
    base_prob = regime_scores.get(current_regime, 0.50)
    
    # 2. Adjust based on ML strategy probabilities
    # We look at MA Crossover and Momentum probabilities. 
    # If they are high (>0.5), it confirms trend strength.
    trend_probs = [v for k, v in strategy_probs.items() if k in ["MA Crossover", "Momentum"]]
    avg_trend_prob = sum(trend_probs) / len(trend_probs) if trend_probs else 0.5
    
    # 3. Incorporate recent price action (momentum)
    # 21-day return
    recent_rets = df["Close"].pct_change(21).iloc[-1] if len(df) >= 21 else 0
    price_score = 0.5 + (recent_rets * 5) # Scale slightly
    price_score = max(0.2, min(0.8, price_score))
    
    # Final Weighted Prob
    # 50% Regime, 30% Strategy ML, 20% Recent Price Action
    final_prob = (base_prob * 0.5) + (avg_trend_prob * 0.3) + (price_score * 0.2)
    
    # Clip
    final_prob = max(0.01, min(0.99, final_prob))

    # 4. Determine label
    if final_prob >= 0.68:
        outlook = "Bullish"
    elif final_prob >= 0.58:
        outlook = "Moderately Bullish"
    elif final_prob >= 0.42:
        outlook = "Neutral / Sideways"
    elif final_prob >= 0.32:
        outlook = "Moderately Bearish"
    else:
        outlook = "Bearish"
        
    # 5. Confidence Score
    # Confidence is high if inputs align
    dispersion = abs(base_prob - avg_trend_prob)
    if dispersion < 0.1 and abs(final_prob - 0.5) > 0.15:
        confidence = "High"
    elif dispersion > 0.3:
        confidence = "Low"
    else:
        confidence = "Medium"
        
    # Expected Volatility (Heuristic from recent realized vol)
    recent_vol = df["Close"].pct_change().rolling(21).std().iloc[-1] * (252**0.5) if len(df) >= 21 else 0.15
    if recent_vol > 0.25:
        vol_label = "High"
    elif recent_vol > 0.15:
        vol_label = "Elevated"
    else:
        vol_label = "Moderate/Low"

    return {
        "outlook": outlook,
        "probability": round(final_prob * 100, 1),
        "confidence": confidence,
        "expected_volatility": vol_label,
        "horizon": "Short-term (Next 21-63 trading days)",
        "disclaimer": (
            "IMPORTANT: This is a probabilistic outlook generated by machine learning models "
            "based on historical market regimes. It is NOT a price prediction or financial advice. "
            "Market conditions can change rapidly, and actual performance may differ significantly "
            "from the estimated outlook. Use at your own risk."
        )
    }
